project:
  type: website
  output-dir: docs # GitHub Pages likes the 'docs' folder for simple deployment

website:
  title: "Panagiotis Zazos | Data Scientist"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Portfolio"
        href: portfolio.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Contact"
        href: contact.qmd

  
  # This enables the toggle switch
  page-footer:
    left: "Â© 2026 Panagiotis Zazos"
    right: "Built with Quarto"

format:
  html:
    theme: litera
    fontsize: 12pt
    # linestretch: 1.5
    css: styles.css
    toc: false